name: "Release Binary"
on:
  push:
    tags:
      - '*.*.*'
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (format x.x.x). If omitted, the tag version will be used (for tag triggers).'
        required: false
        default: ''
jobs:
  build:
    runs-on: macos-15
    env:
        RELEASE_REPO: "FlickerSoul/MyPrivateLibRelease"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: Determine Version
        id: determine_version
        env:
          INPUT_VERSION: ${{ github.event.inputs.version }}
        run: |
          SDK_VERSION=$(python3 ./scripts/sdk_tools/version.py)
          echo "version=${SDK_VERSION}" >> $GITHUB_OUTPUT
          echo "Determined version: ${SDK_VERSION}"
      - name: Setup Signing
        if: false # skipped
        env:
          BUILD_CERT_BASE64: ${{ secrets.BUILD_SIGNING_CERT }}
          BUILD_CERT_PWD: ${{ secrets.BUILD_SIGNING_CERT_PWD }}
          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
        run: |
          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
          APPLE_TRUST_CERTIFICATE_PATH=$RUNNER_TEMP/apple_trust.cer
          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db

          echo -n "$BUILD_CERT_BASE64" | base64 --decode -o $CERTIFICATE_PATH

          # temporary keychain
          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH

          # add apple's root certificate
          curl -o $APPLE_TRUST_CERTIFICATE_PATH https://www.apple.com/certificateauthority/AppleWWDRCAG3.cer
          security import $APPLE_TRUST_CERTIFICATE_PATH -k $KEYCHAIN_PATH

          # import certificate to keychain
          security import $CERTIFICATE_PATH -P "$BUILD_CERT_PWD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
          security set-key-partition-list -S apple-tool:,apple: -k "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
          security list-keychain -d user -s $KEYCHAIN_PATH

          # show identities
          security find-identity -v $KEYCHAIN_PATH

          # export keychain path
          echo "KEYCHAIN_PATH=$KEYCHAIN_PATH" >> $GITHUB_ENV
      - name: Install xcbeautify
        run: brew install --quiet xcbeautify
      - name: Build XCFramework
        run: python3 ./scripts/archive_proj.py
      - name: Upload XCFramework Artifact
        uses: actions/upload-artifact@v7
        with:
          name: XCFramework
          path: ${{ env.XCFRAMEWORK_ZIP_OUTPUT }}
          if-no-files-found: error
          archive: false
      - name: Checkout the release repository
        uses: actions/checkout@v6
        with:
          repository: ${{ env.RELEASE_REPO }}
          token: ${{ secrets.BINARY_REPO_TOKEN }}
          path: binary-repo
      - name: Upload Release
        env:
          GITHUB_TOKEN: ${{ secrets.BINARY_REPO_TOKEN }}
          SDK_VERSION: ${{ steps.determine_version.outputs.version }}
        run: python3 ./scripts/upload_release.py
